let nombre = 'Martin';
let apellido = 'Alturria';
let estudiante = nombre.concat(" ", apellido);
let estudianteMayus = estudiante.toUpperCase();
let estudianteMinus = estudiante.toLowerCase();
let primerLetraNombre = nombre[0];
let ultimaLetraApellido = apellido.charAt(apellido.length - 1);
let eliminaEspacio = estudiante.trim();
let estaelNombre = estudiante.includes(nombre);